@BookApi_HostAddress = http://localhost:5264

GET {{BookApi_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{BookApi_HostAddress}}/api/auth/register-user/
Content-Type: application/json

{
    "userName": "testuser",
    "password": "testpassword123"
}

###
POST {{BookApi_HostAddress}}/api/auth/register-user/
Content-Type: application/json

{
    "userName": "testuser2",
    "password": "testpassword123"
}

###
POST {{BookApi_HostAddress}}/api/auth/login-user/
Content-Type: application/json

{
    "userName": "testuser",
    "password": "testpassword123"
}

###
POST {{BookApi_HostAddress}}/api/auth/login-user/
Content-Type: application/json

{
    "userName": "testuser2",
    "password": "testpassword123"
}

###
GET {{BookApi_HostAddress}}/api/books/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA0MTM5OSwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDM3Nzk5LCJuYmYiOjE3ODkwMzc3OTl9.PiCmHF8zNDP92CmY-IHj3L-cu-jp6LkFFwlnzKZ0yuE; expires=Fri, 11 Sep 2026 10:56:39 GMT; path=/; secure; samesite=none; httponly

###
PUT {{BookApi_HostAddress}}/api/books/2
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA0MTM5OSwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDM3Nzk5LCJuYmYiOjE3ODkwMzc3OTl9.PiCmHF8zNDP92CmY-IHj3L-cu-jp6LkFFwlnzKZ0yuE; expires=Fri, 11 Sep 2026 10:56:39 GMT; path=/; secure; samesite=none; httponly
Content-Type: application/json

{
    "Title": "Frankenstein",
    "Author": "mary Shelley",
    "YearPublished": "1818"
}

###
DELETE {{BookApi_HostAddress}}/api/books/3
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA0ODg4NywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDQ1Mjg3LCJuYmYiOjE3ODkwNDUyODd9.kBI-LB_ZXrQayWWmne8TuqPjxqOQdOQTF3Y2GVrmeLg; expires=Fri, 11 Sep 2026 13:01:27 GMT; path=/; secure; samesite=none; httponly


### 
POST {{BookApi_HostAddress}}/api/quotes/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA0ODg4NywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDQ1Mjg3LCJuYmYiOjE3ODkwNDUyODd9.kBI-LB_ZXrQayWWmne8TuqPjxqOQdOQTF3Y2GVrmeLg; expires=Fri, 11 Sep 2026 13:01:27 GMT; path=/; secure; samesite=none; httponly
Content-Type: application/json

{
    "Content": "Hello"
}

###
Get {{BookApi_HostAddress}}/api/quotes/
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA0ODg4NywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDQ1Mjg3LCJuYmYiOjE3ODkwNDUyODd9.kBI-LB_ZXrQayWWmne8TuqPjxqOQdOQTF3Y2GVrmeLg; expires=Fri, 11 Sep 2026 13:01:27 GMT; path=/; secure; samesite=none; httponly

###
DELETE {{BookApi_HostAddress}}/api/quotes/2
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA0ODg4NywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDQ1Mjg3LCJuYmYiOjE3ODkwNDUyODd9.kBI-LB_ZXrQayWWmne8TuqPjxqOQdOQTF3Y2GVrmeLg; expires=Fri, 11 Sep 2026 13:01:27 GMT; path=/; secure; samesite=none; httponly

###
DELETE {{BookApi_HostAddress}}/api/auth/account
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJCb29rQXBpQ2xpZW50IiwiaXNzIjoiQm9va0FwaSIsImV4cCI6MTc4OTA1MjE5NCwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRlc3R1c2VyIiwiaWF0IjoxNzg5MDQ4NTk0LCJuYmYiOjE3ODkwNDg1OTR9.1s7g59vv3Ow-6kX0AwiCADHXF4C3oUWEpu21B2ZzHm4; expires=Fri, 11 Sep 2026 13:56:34 GMT; path=/; secure; samesite=none; httponly


